name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - run: dotnet build --configuration Release
    - run: dotnet test
